/* CommVault Protected Virtual Machines report
Create Date:        2022-06-16, last updated 2024-07-31
Author:             Tom Ling
Purpose: 			Returns backup job data by individual VM from Commvault database. 
Description:        Returns list of all VMs protected by backup jobs where the backup type for 
					the VM is Full or Synthetic Full and the VM protection status is Success or 
					Partial Success. The data attempts to replicate the Protected VMs table in 
					the Application Size Report which is set up in Commcell console to generate 
					every month. This SQL query does not fully replicate it due to lack of 
					information about where some of the data comes from (see Usage section). 
Call by:            Audit Excel file
Database:  			[Commvault Database]
Used By:            FT Operations
Parameter(s):       N/A
Usage:              Job IDs in the result set will contain fewer values than the equivalent 
					Commcell reports. This is because Commvault deletes old jobs from the database
					when the backup becomes aged, and possibly for other reasons. Therefore, 
					Commcell reports will include jobs that only existed for a brief period. 
					All datetime fields are currently in UTC. Time zone conversion is not possible
					until the SQL Server instance on which CommServ is running is updated to 2016+. 
					No attempt made to output VM Guest Tools, Hardware Version, App Aware Status, 
					Availability Zone, or Owners.
****************************************************************************************************
SUMMARY OF CHANGES
Date(yyyy-mm-dd)    Author              Comments
------------------- ------------------- ------------------------------------------------------------
2024-07-31			Tom Ling			Portfolio version.
2022-06-16          Tom Ling			Initial script completed.
***************************************************************************************************/


SELECT
	result.*
FROM (
	SELECT 
		/* Unique ID for each backup job. 
		Commcell prunes old or irrelevant backup jobs over time - the details are not clear. 
		But it means that the jobs in the result set may not match the jobs in past reports generated by Commcell. */
		ccvmbi.[jobid] AS [Job ID]
		/* A Job ID may cover multiple VMs, which is the purpose of this script. */
		,ccvmbi.[vmname] AS [Machine Name]
		--,ccvmbi.[vmclientid]
		/* Agent value */
		,CASE WHEN ccvmbi.[proxy] = '' THEN 'N/A'
			ELSE ccvmbi.[proxy] 
		END AS [Agent]
		/* VM status (takes values: Success, Failed, NULL, In Progress, Waiting, PartialSuccess) */
		,ccvmbi.[vmstatus] AS [Status]

		/* Size measures */
		/* VM Size - represents the total storage on all the protected disks. */
		,ROUND(CAST(ccvmbi.[vmsizebytes] AS bigint)*1.0/1024/1024/1024,3) AS [Virtual Machine Size (GB)]
		/* Backup Size - the amount of data transferred and written in this backup job for this VM. */
		,ROUND(CAST(ccvmbi.[vmbackupsizebytes] AS bigint)*1.0/1024/1024/1024,3) AS [Backup Size (GB)]
		/* Guest Size - the occupied space on the VM's protected disks. */
		,ROUND(CAST(ccvmbi.[vmguestsizebytes] AS bigint)*1.0/1024/1024/1024,3) AS [Guest Size (GB)]

		/* Client computer name, matches Commcell list of clients. */
		--,ccvmbi.[virtualizationclient] AS [Client]
		--,ccvmbi.[virtualizationclientid]
		/* Name of subclient. */
		--,ccvmbi.[subclient] AS [Subclient]
		/* Name of backup set. */
		--,ccvmbi.[backupset] AS [Backup Set]
		/* Storage Policy */
		--,ccvmbi.[data_sp] AS [Storage Policy]
		--,ccvmbi.[vmGUID]
		--,ccvmbi.[vmhost] AS [VM Host]
		--,ccvmbi.[proxy]

		/* VM backup start date and time (different for each VM within a job) */
		--,ccvmbi.[startdateunixsec]
		--,ccvmbi.[enddateunixsec]
		/* This needs time zone conversion to local UK time. SQL Server needs to be updatd to 2016+ first - for now, use UTC time. */
		,ccvmbi.[startdate] AS [Start Time] 
		,ccvmbi.[enddate] AS [End Time] 

		/* VM Guest Tools - can't find this data in CommServ */
		,'' AS [VM Guest Tools]
		/* Hardware Version - can't find this data in CommServ */
		,'' AS [Hardware Version]
		/* Operating System */
		,cnciv.[OSName] AS [Operating System]

		/* Backup Type (takes values: Incremental, Full, Differential, or Synthetic Full) */
		--,ccvmbi.[backuplevelInt]
		,ccvmbi.[backuplevel] AS [Backup Type]

		/* Other fields, not required */
		--,ccvmbi.[vmtransportmode]
		,'' AS [Transport Mode]
		,ccvmbi.[vmcbtstatus] AS [CBT Status]
		,'' AS [App Aware Status]
		,'' AS [Availability Zone]
		,'' AS [Owners]

		--,ccbi.[jobstatus]
		--,ccbi.[isAged]
		/* Reason the backup job failed */
		,ISNULL(ccvmbi.[failureReason],'') AS [Failure Reason]
		--,ccbi.[inPrimaryCopy]
	FROM 
		/* Base table: VM backup info */
		[CommServ].[dbo].[CommCellVMBackupInfo] ccvmbi
		LEFT JOIN (
			/* Subquery to add relevant fields from Backup Info table for filtering */
			SELECT 
				[jobid] AS [ccbijobid]
				--,[jobstatus]
				--,[isAged]
				,[idataagent]
				,[inPrimaryCopy] 
			FROM 
				[CommServ].[dbo].[CommCellBackupInfo]) ccbi ON ccvmbi.[jobid] = ccbi.[ccbijobid]
		/* Client info table that contains OS name */
		LEFT JOIN [CommServ].[dbo].[CNClientInfoView] cnciv ON ccvmbi.[vmclientid] = cnciv.[ID]
	WHERE 
		/* Include only rows with Primary Copy > 0. Not sure what this means but it helps 
		the data match what is shown in Commcell console for any given VM. */
		ccbi.[inPrimaryCopy] > 0
) result

WHERE
	/* Include only VMs successfully backed up */
	result.[Status] IN ('Success', 'PartialSuccess')

	/* Include only Full and Synthetic Full backups */
	AND result.[Backup Type] IN ('Full', 'SyntheticFull')

	/* Filter by Job ID */
	--AND result.[Job ID] = 1334577
	
	/* Filter by name */
	--AND result.[Machine Name] LIKE '%%' 
	
	/* Filter by date */
	--AND result.[Start Time] >= CAST('2022-05-01' AS datetime2)
	--AND result.[Start Time] < CAST('2022-06-01 02:00:01' AS datetime2)

ORDER BY 
	result.[Job ID] DESC